name: personal_finance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Translations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  turkmen_localization_support: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.11
  slang_build_runner: ^3.31.0

flutter:
  uses-material-design: true
